# Generated by Django 4.2.2 on 2023-08-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='animeList',
            field=models.JSONField(default={'title': 'nothing yet'}),
        ),
    ]
