# Generated by Django 4.2.2 on 2023-09-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_animelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='animeList',
            field=models.JSONField(default={'results': [{'title': 'nothingyet'}]}),
        ),
    ]
