# Generated by Django 4.2.2 on 2023-09-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_animelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='animeList',
            field=models.JSONField(default={'results': [{'id': 'nothingyet', 'title': 'nothingyet'}]}),
        ),
    ]
